import React from 'react';
import {AbsoluteFill,Audio,Img,interpolate,staticFile,useCurrentFrame} from 'remotion';

// FlowMinute Oct 12: all product representations are clearly labeled illustrative UI.
// The shapes show how a product is intended to work, not actual screen recordings.
const P={navy:'#071426',cyan:'#39DDF3',teal:'#16C8B8',white:'#EAFBFF',amber:'#FFC66B',muted:'#A8BDD0'};
const font='Inter,Segoe UI,Arial,sans-serif';
const enter=(f:number,start:number)=>interpolate(f,[start,start+18],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp'});
const pane:React.CSSProperties={background:'linear-gradient(145deg,rgba(12,33,54,.96),rgba(9,22,44,.98))',border:'2px solid #2D637A',borderRadius:28,boxShadow:'0 24px 80px #01091499',overflow:'hidden'};
const Txt:React.FC<{children:React.ReactNode;size?:number;color?:string;weight?:number;style?:React.CSSProperties}>=({children,size=30,color=P.white,weight=700,style})=><div style={{fontSize:size,color,fontWeight:weight,lineHeight:1.14,...style}}>{children}</div>;
const Env:React.FC<{f:number;pic?:boolean}>=({f,pic=false})=><AbsoluteFill style={{background:P.navy,overflow:'hidden'}}>{pic&&<Img src={staticFile('office-desks.jpg')} style={{position:'absolute',inset:0,width:'100%',height:'100%',objectFit:'cover',opacity:.22,filter:'saturate(1.3) blur(3px)',transform:'scale('+(1.08+f/25000)+')'}}/>}<div style={{position:'absolute',inset:0,background:'radial-gradient(circle at 18% 20%,#103E5266,transparent 38%),radial-gradient(circle at 84% 72%,#244FA244,transparent 39%)'}}/><div style={{position:'absolute',left:'-20%',top:40,width:'140%',height:1,background:'#39DDF342',transform:'rotate(-8deg)'}}/><div style={{position:'absolute',left:'-20%',top:'80%',width:'140%',height:1,background:'#39DDF329',transform:'rotate(-8deg)'}}/></AbsoluteFill>;
const Brand:React.FC<{mobile?:boolean}>=({mobile})=><div style={{color:P.cyan,fontWeight:950,letterSpacing:3,fontSize:mobile?28:24}}>FM  /  FLOWMINUTE LAB</div>;
const Badge:React.FC<{children:React.ReactNode}>=({children})=><div style={{display:'inline-block',fontSize:19,fontWeight:850,padding:'9px 16px',borderRadius:30,background:'#21CBBA22',color:P.teal,border:'1px solid #2BBEA877',letterSpacing:1}}>{children}</div>;
const Dot:React.FC<{x:number;y:number;color:string}>=({x,y,color})=><div style={{width:23,height:23,borderRadius:'50%',position:'absolute',left:x,top:y,background:color,boxShadow:'0 0 22px '+color}}/>;
const Row:React.FC<{label:string;value:string;accent?:boolean}>=({label,value,accent=false})=><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginTop:14,borderRadius:14,padding:'15px 18px',background:accent?'#164B5A':'#17304B',border:accent?'1px solid #41E3CC':'1px solid #29475B'}}><Txt size={25} color={P.muted}>{label}</Txt><Txt size={31} color={accent?P.teal:P.white}>{value}</Txt></div>;

const Bill:React.FC<{f:number;mobile?:boolean;forceSix?:boolean}>=({f,mobile=false,forceSix=false})=>{const six=mobile?Boolean(forceSix):f%220>114;return <div style={{...pane,padding:mobile?35:34,width:'100%',boxSizing:'border-box',height:'100%',position:'relative'}}><Badge>ILLUSTRATIVE TOOL · NOT A LIVE SCREEN</Badge><Txt size={mobile?58:45} style={{marginTop:25}}>Split the dinner bill</Txt><Txt size={mobile?27:24} color={P.muted} style={{marginTop:10}}>Edit a number. See a different answer.</Txt><div style={{marginTop:26}}><Row label="Total bill" value="₹2,400"/><Row label="People" value={six?'−   6   +':'−   4   +'}/></div><div style={{marginTop:30,padding:'25px 30px',borderRadius:22,background:'linear-gradient(115deg,#1BA99A,#1661A8)',border:'1px solid #62F3F1'}}><Txt color="#EFFFFF" size={21}>EACH PERSON PAYS</Txt><Txt color="white" size={mobile?83:76}>₹{six?'400':'600'}</Txt></div><div style={{display:'flex',gap:9,marginTop:20,alignItems:'center'}}><Dot x={-200} y={-200} color={P.teal}/><Txt size={mobile?27:21} color={P.muted}>Illustration: 2400 ÷ {six?'6':'4'} = {six?'400':'600'}</Txt></div></div>};
const Spreadsheet:React.FC<{f:number;mobile?:boolean}>=({f,mobile=false})=>{const after=f%270>132;return <div style={{...pane,padding:mobile?30:34,height:'100%',boxSizing:'border-box'}}><Badge>ILLUSTRATIVE WORKFLOW · NOT PRODUCT FOOTAGE</Badge><Txt size={mobile?52:41} style={{marginTop:22}}>Spreadsheet · October 10</Txt><div style={{marginTop:24,background:'#EFF5FA',borderRadius:16,overflow:'hidden',color:'#152B3D'}}><div style={{background:'#1C786E',padding:'14px 19px',fontSize:22,color:'white',fontWeight:900}}>Orders.csv  ·  AI assistant</div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',fontSize:mobile?28:25}}>{[['ITEM','QUANTITY'],['USB hub',' 04 '],['Cable',after?'7':' 7 pcs '],['Mouse',after?'2':' 2 units '],['Monitor','1']].flatMap((row,i)=>row.map((v,j)=><div key={i+'-'+j} style={{padding:'18px 16px',background:i===0?'#D7ECE8':i%2?'#F7FAFD':'#EAF0F6',borderBottom:'1px solid #CBD6DF',fontWeight:i===0?900:600}}>{v}</div>))}</div></div><div style={{marginTop:24,padding:'19px 22px',background:'#123E4E',borderRadius:17,border:'1px solid #31AFAF'}}><Txt size={mobile?28:23} color={P.teal}>{after?'REVIEW THE CLEANED VALUES':'AI ASSISTANCE IN THE EDITOR'}</Txt><Txt size={mobile?24:21} color={P.white} style={{marginTop:7}}>{after?'A suggested change still needs checking.':'Keep context while working in a spreadsheet.'}</Txt></div></div>};
const Study:React.FC<{f:number}>=({f})=>{const more=f%260>140;return <div style={{...pane,padding:35,width:'100%',height:'100%',boxSizing:'border-box'}}><Badge>CONCEPT DIAGRAM · NOT APP FOOTAGE</Badge><Txt size={41} style={{marginTop:21}}>Understand probability visually</Txt><Txt size={26} color={P.muted} style={{marginTop:14}}>How many blue balls are in the bag?</Txt><div style={{display:'flex',gap:25,alignItems:'center',marginTop:24}}>{Array.from({length:more?6:5},(_,i)=><div key={i} style={{width:74,height:74,background:i<(more?3:2)?'#39DDF3':'#FFBB6D',borderRadius:'50%',boxShadow:'inset -12px -13px 15px #00000055'}}/>)}</div><div style={{display:'flex',gap:20,alignItems:'center',marginTop:26}}><Txt size={77} color={P.teal}>{more?'3 / 6':'2 / 5'}</Txt><Txt size={27} color={P.muted}>Change the assumption. Recheck the result.</Txt></div></div>};
const Compare:React.FC=()=><div style={{...pane,padding:34,width:'100%',height:'100%',boxSizing:'border-box'}}><Badge>ILLUSTRATIVE DECISION GUIDE</Badge><Txt size={43} style={{marginTop:20}}>Three ways to finish the work</Txt><div style={{display:'flex',gap:17,marginTop:30}}>{[['MANUAL','Fast setup','Repeated effort'],['TEMPLATE','Reusable','Needs updating'],['AUTOMATION','Scalable','Needs testing']].map(([a,b,c],i)=><div key={a} style={{flex:1,borderRadius:19,padding:'26px 20px',background:i===2?'#125864':'#132D4A',border:'1px solid #42C8CD'}}><Txt size={24} color={P.teal}>{a}</Txt><Txt size={24} style={{marginTop:23}}>{b}</Txt><Txt size={22} color={P.muted} style={{marginTop:16}}>{c}</Txt></div>)}</div></div>;
const Flow:React.FC<{mobile?:boolean}>=({mobile=false})=><div style={{...pane,padding:36,width:'100%',height:'100%',boxSizing:'border-box'}}><Badge>CONCEPT — USER'S VIEW</Badge><Txt size={43} style={{marginTop:24}}>A question can become a useful interface</Txt><div style={{display:'flex',flexDirection:mobile?'column':'row',alignItems:mobile?'stretch':'center',gap:mobile?13:14,marginTop:mobile?30:45}}>{[['ASK','One useful question'],['SEE','Text + controls'],['ADJUST','Change the inputs'],['CHECK','Verify the result']].map(([a,b],i)=><React.Fragment key={a}><div style={{flex:mobile?'none':1,display:mobile?'flex':'block',justifyContent:'space-between',alignItems:'center',borderRadius:18,background:i===2?'#125E63':'#19354F',padding:mobile?'22px 25px':'23px 14px',minHeight:mobile?83:150}}><Txt size={mobile?38:28} color={P.cyan}>{a}</Txt><Txt size={mobile?29:21} style={{marginTop:mobile?0:18}}>{b}</Txt></div>{!mobile&&i<3&&<Txt size={36} color={P.teal}>→</Txt>}</React.Fragment>)}</div></div>;
const Limit:React.FC=()=><div style={{...pane,padding:36,height:'100%',boxSizing:'border-box'}}><Badge>IMPORTANT LIMITATIONS</Badge>{[['Availability varies','Depends on rollout, plan and client'],['Not every prompt needs a widget','Plain text can still be the best answer'],['Not a deployed standalone app','A chat tool is not a published website'],['Verify sensitive calculations','Check inputs, sources, permissions']].map(([a,b])=><div key={a} style={{padding:'19px 10px',borderBottom:'1px solid #356075'}}><Txt size={29} color={P.white}>{a}</Txt><Txt size={21} color={P.muted} style={{marginTop:8}}>{b}</Txt></div>)}</div>;
const Prompts:React.FC=()=><div style={{...pane,padding:35,height:'100%',boxSizing:'border-box'}}><Badge>IDEAS TO TRY IN CHATGPT</Badge><Txt size={39} style={{marginTop:26}}>Start with a real problem</Txt>{['Build a bill splitter with an editable total and people count.','Explain probability with a diagram where I can change inputs.','Compare three approaches in a side-by-side decision table.'].map((x,i)=><div key={x} style={{marginTop:24,background:i===0?'#16545C':'#183B56',borderRadius:15,padding:18,border:'1px solid #45778E'}}><Txt size={23}>{i+1}.  {x}</Txt></div>)}</div>;
type Kind='bill'|'office'|'study'|'compare'|'flow'|'limit'|'prompts';
const Graphic:React.FC<{kind:Kind;f:number;mobile?:boolean;forceSix?:boolean}>=({kind,f,mobile,forceSix})=>kind==='bill'?<Bill f={f} mobile={mobile} forceSix={forceSix}/>:kind==='office'?<Spreadsheet f={f} mobile={mobile}/>:kind==='study'?<Study f={f}/>:kind==='compare'?<Compare/>:kind==='flow'?<Flow mobile={mobile}/>:kind==='limit'?<Limit/>:<Prompts/>;
type Beat={from:number;to:number;kind:Kind;kicker:string;headline:string;body:string;take:string};
const beats:Beat[]=[
 {from:0,to:20,kind:'flow',kicker:'OCTOBER 2026 · NEW CHAT EXPERIENCE',headline:'WHAT IF AI BUILT THE TOOL?',body:'Interactive answers, not just paragraphs.',take:'The interface can adapt to your question.'},
 {from:20,to:46,kind:'compare',kicker:'WHY THIS MATTERS',headline:'TEXT IS NOT ALWAYS ENOUGH',body:'Some choices are easier when you can adjust them.',take:'Compare alternatives without losing the context.'},
 {from:46,to:77,kind:'bill',kicker:'EXAMPLE 01 · THE BILL',headline:'4 PEOPLE → 6 PEOPLE',body:'₹2,400 divided fairly — then change the input.',take:'The example is illustrative, not a live demo.'},
 {from:77,to:111,kind:'study',kicker:'EXAMPLE 02 · LEARNING',headline:'MAKE THE IDEA VISIBLE',body:'Change the assumptions; see what changes.',take:'Interactive graphics still need correct math.'},
 {from:111,to:146,kind:'compare',kicker:'EXAMPLE 03 · WORKFLOW CHOICES',headline:'COMPARE BEFORE YOU AUTOMATE',body:'Manual, reusable templates, or automation?',take:'A decision aid is not permission to access files.'},
 {from:146,to:172,kind:'flow',kicker:'FROM PROMPT TO INTERFACE',headline:'ASK → ADJUST → CHECK',body:'Buttons and charts when they are useful.',take:'A simple paragraph can also be the best result.'},
 {from:172,to:198,kind:'limit',kicker:'THE CATCH',headline:'NOT EVERYTHING IS AVAILABLE',body:'Rollout, plan, permissions and client matter.',take:'Chat interactions are not standalone deployed apps.'},
 {from:198,to:222,kind:'prompts',kicker:'YOUR TURN',headline:'WHICH TOOL WOULD YOU BUILD?',body:'Try the prompt examples, then verify the answer.',take:'Useful > flashy. Tell us your next tool idea.'}
];
export const IntelligentUILong:React.FC=()=>{const f=useCurrentFrame(),s=f/24,st=beats.find(b=>s>=b.from&&s<b.to)||beats[beats.length-1],o=enter(f,st.from*24);return <AbsoluteFill style={{color:P.white,fontFamily:font}}><Env f={f} pic={s<46}/><div style={{position:'absolute',left:74,top:39,right:74,display:'flex',justifyContent:'space-between'}}><Brand/><Badge>GPT-6 · INTELLIGENT UI</Badge></div><div style={{position:'absolute',left:80,top:165,width:750,opacity:o,transform:'translateY('+((1-o)*20)+'px)'}}><Txt color={P.teal} size={24}>{st.kicker}</Txt><Txt size={62} style={{marginTop:29,lineHeight:1.08}}>{st.headline}</Txt><Txt size={32} color={P.muted} style={{marginTop:33}}>{st.body}</Txt><div style={{marginTop:56,padding:'21px 22px',borderLeft:'6px solid '+P.cyan,background:'#14364A99'}}><Txt size={27}>{st.take}</Txt></div></div><div style={{position:'absolute',left:890,top:218,right:70,height:635,opacity:o,transform:'perspective(1500px) rotateY(-2deg) translateY('+((1-o)*16)+'px)'}}><Graphic kind={st.kind} f={f}/></div><div style={{position:'absolute',bottom:44,left:77,right:77,display:'flex',justifyContent:'space-between'}}><Txt size={19} color={P.muted}>ILLUSTRATIVE UI RECONSTRUCTIONS · SOURCE: OPENAI, OCT 7 2026</Txt><Txt size={19} color={P.cyan}>FLOWMINUTE LAB</Txt></div><div style={{position:'absolute',bottom:0,height:6,background:P.teal,width:(f/(222*24)*100)+'%'}}/><Audio src={staticFile('voice-long-007.mp3')}/></AbsoluteFill>};
type ShortBeat={from:number;to:number;kind:Kind;headline:string;sub:string;label:string;forceSix?:boolean};
const a15:ShortBeat[]=[{from:0,to:6,kind:'flow',headline:'CAN AI BUILD A TOOL?',sub:'Not just five paragraphs.',label:'GPT-6 INTELLIGENT UI'},{from:6,to:18,kind:'bill',headline:'₹2,400. FOUR FRIENDS.',sub:'Each pays ₹600.',label:'INTERACTIVE EXAMPLE'},{from:18,to:27,kind:'bill',headline:'TWO FRIENDS JOIN.',sub:'Six people now pay ₹400.',label:'ONE INPUT CHANGES',forceSix:true},{from:27,to:37,kind:'flow',headline:'ASK. ADJUST. CHECK.',sub:'Would you use this in chat?',label:'ILLUSTRATIVE · ROLLOUT VARIES'}];
const a16:ShortBeat[]=[{from:0,to:8,kind:'office',headline:'AI IN YOUR SPREADSHEET?',sub:'ONLYOFFICE 10 was announced October 10.',label:'NEW PRODUCT UPDATE'},{from:8,to:21,kind:'office',headline:'WORK IN THE EDITOR.',sub:'Ask for assistance within the file.',label:'CONCEPT WORKFLOW'},{from:21,to:31,kind:'office',headline:'REVIEW THE OUTPUT.',sub:'Never trust a clean-looking column blindly.',label:'CHECK THE SUGGESTIONS'},{from:31,to:40,kind:'office',headline:'WOULD YOU TRY IT?',sub:'Check your edition and privacy settings.',label:'NOT A HANDS-ON TEST'}];
const ShortBase:React.FC<{kind:15|16}>=({kind})=>{const f=useCurrentFrame(),sec=f/30,beats=kind===15?a15:a16,st=beats.find(x=>sec>=x.from&&sec<x.to)||beats[beats.length-1],o=enter(f,st.from*30);return <AbsoluteFill style={{color:P.white,fontFamily:font}}><Env f={f} pic={kind===16}/><div style={{position:'absolute',top:110,left:74,right:74}}><Brand mobile/><div style={{marginTop:135,opacity:o,transform:'translateY('+((1-o)*28)+'px)'}}><Badge>{st.label}</Badge><Txt size={78} style={{marginTop:38,letterSpacing:-2.5,lineHeight:1.05}}>{st.headline}</Txt><Txt size={37} color={P.muted} style={{marginTop:29}}>{st.sub}</Txt></div></div><div style={{position:'absolute',left:72,right:72,top:670,height:780,opacity:o,transform:'translateY('+((1-o)*20)+'px)'}}><Graphic kind={st.kind} f={f} mobile forceSix={st.forceSix}/></div><div style={{position:'absolute',top:1500,left:72,right:72,background:'#082039DD',border:'1px solid #3E7186',borderRadius:18,padding:'25px 18px'}}><Txt size={32} color={P.cyan}>{kind===15?'GPT-6 · OFFICIAL RELEASE OCT 7':'ONLYOFFICE 10.0 · OFFICIAL RELEASE OCT 10'}</Txt><Txt size={28} color={P.muted} style={{marginTop:10}}>Illustrative reconstruction · Feature access varies.</Txt></div><div style={{position:'absolute',bottom:80,left:75,right:75,display:'flex',justifyContent:'space-between'}}><Txt size={22} color={P.muted}>FLOWMINUTE LAB</Txt><Txt size={22} color={P.teal}>AI · AUTOMATION · PRODUCTIVITY</Txt></div><div style={{position:'absolute',bottom:0,left:0,height:9,background:P.teal,width:(f/((kind===15?37:40)*30)*100)+'%'}}/><Audio src={staticFile(kind===15?'voice-v15.mp3':'voice-v16.mp3')}/></AbsoluteFill>};
export const IntelligentUIShort:React.FC=()=> <ShortBase kind={15}/>;
export const OnlyOfficeShort:React.FC=()=> <ShortBase kind={16}/>;
export const IntelligentUIThumbnail:React.FC=()=> <AbsoluteFill style={{fontFamily:font,color:P.white}}><Env f={50} pic/><div style={{position:'absolute',top:70,left:90}}><Brand/></div><div style={{position:'absolute',left:90,top:235,width:890}}><Txt size={107} style={{lineHeight:.99}}>CHATGPT BUILDS A TOOL?</Txt><Txt size={43} color={P.cyan} style={{marginTop:45}}>GPT-6 · INTELLIGENT UI</Txt><div style={{marginTop:35,width:590,height:9,background:P.teal,borderRadius:5}}/></div><div style={{position:'absolute',left:1060,top:210,width:760,height:640,transform:'rotate(-4deg)'}}><Bill f={190}/></div></AbsoluteFill>;
